### ISSUE TITLE
No such directory in aio-builder

### ISSUE THREAD

**Issue by jwaes** [axelor/axelor-docker#13]
When running `$ docker build -t axelor/aio-builder .` i get this error: (from stacktrace)

```
> Task :modules:axelor-exception:compileJava
> Task :modules:axelor-bank-payment:xjc
> Task :modules:axelor-docusign:shadowDocusignDeps

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npm-install'.
> A problem occurred starting process 'command 'npm''

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':npm-install'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)

[...]


Caused by: java.io.IOException: Cannot run program "npm" (in directory "/app/src/axelor-erp/build/webapp"): error=2, No such file or directory
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 7 more
```

**Comment by FitzChevalerie-22** [comment]
Same problem.
I think is in the https://github.com/axelor/axelor-open-suite , but where exactly ?
